const T = "transition-colors duration-300";
const H = "text-zinc-900 dark:text-white";
const B = "text-zinc-700 dark:text-zinc-300";
const S = `py-20 ${T}`;
const CN = "container mx-auto";
const RD = "rounded-lg";
const ACTION = "text-brand-500 dark:text-brand-400";
const M6 = "mb-6";
const M12 = "mb-12";

export const CLASSES = {
	layout: {
		body: `bg-zinc-50 dark:bg-zinc-950 text-zinc-900 dark:text-zinc-100 font-sans min-h-screen flex flex-col ${T}`,
		header: `border-b sticky top-0 z-50 ${T}`,
		headerBrand: "text-2xl font-bold text-brand-50 hover:text-white transition-colors",
		footer: `bg-zinc-200 dark:bg-zinc-900 text-zinc-900 dark:text-zinc-400 py-12 border-t border-zinc-300 dark:border-zinc-800 ${T} text-center`,
		section: S,
		sectionWhite: `${S} bg-white dark:bg-zinc-950`,
		sectionMuted: `${S} bg-zinc-100 dark:bg-zinc-800`,
		sectionDark: `${S} bg-brand-500 text-white`,
		container: `${CN} px-6 lg:px-12`,
		containerHome: `${CN} px-12 lg:px-32`,
		containerNarrow: "max-w-5xl mx-auto",
		containerArticle: "max-w-4xl mx-auto",
		pagePadding: "py-20",
		headerContainer: `${CN} px-4 py-4 flex justify-between items-center`,
		headerLogo: "h-12 w-auto",
		hero: `bg-brand-50 dark:bg-[var(--hero-dark-bg)] py-20 lg:py-32 ${T}`,
		grid2: "grid grid-cols-1 lg:grid-cols-2 gap-16",
		grid3: "grid grid-cols-1 md:grid-cols-3 gap-8",
		grid4: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8",
		stackLarge: "space-y-12",
		stackMedium: "space-y-8",
		stackSmall: "space-y-4",
		navHorizontal: "flex space-x-8",
		navVertical: "space-y-2",
		aboutHeader: "bg-zinc-50 dark:bg-zinc-800 py-20 border-b border-zinc-100 dark:border-zinc-900",
	},
	typography: {
		h1: `${H} text-4xl lg:text-6xl font-extrabold leading-tight`,
		h1Page: `${H} text-4xl lg:text-5xl font-extrabold leading-tight`,
		h1Medium: `${H} text-4xl font-extrabold leading-tight`,
		h2: `${H} text-3xl font-bold`,
		h2Page: `${H} text-2xl font-bold`,
		h2Centered: `${H} text-3xl font-bold ${M12}`,
		h3: `${H} text-xl font-bold`,
		lead: `${B} text-xl leading-relaxed`,
		body: `${B} text-lg leading-relaxed`,
		link: "text-brand-600 dark:text-brand-400 hover:underline transition-colors",
		action: `${ACTION} font-bold flex items-center gap-1 group-hover:gap-2 transition-all`,
		navLink: "text-brand-100/70 hover:text-white font-medium transition-all duration-200",
		navLinkActive: "text-white font-bold border-b-2 border-brand-400 pb-1",
		date: "text-sm text-zinc-500 dark:text-zinc-400",
		roleBadge: `${ACTION} font-bold mb-8 uppercase tracking-widest text-xs`,
		footerHeading: "text-lg font-bold mb-4 text-zinc-900 dark:text-zinc-200",
		footerLink: "hover:text-brand-600 dark:hover:text-brand-400 transition-colors",
		footerText: "text-zinc-700 dark:text-zinc-500 text-sm leading-relaxed",
		listItem: "flex items-start gap-2 text-zinc-600 dark:text-zinc-400",
		listItemLabel: "text-zinc-700 dark:text-zinc-300 leading-tight font-medium",
		copyright: "border-t border-zinc-300 dark:border-zinc-800 mt-12 pt-8 text-center text-zinc-600 dark:text-zinc-600 text-sm",
	},
	prose: {
		base: `prose prose-lg prose-zinc dark:prose-invert max-w-none prose-headings:${H} prose-a:text-brand-600 dark:prose-a:text-brand-400`,
	},
	button: {
		base: `${RD} font-bold transition-colors duration-200 px-8 py-4`,
		primary: "bg-brand-500 text-white hover:bg-brand-600",
		secondary: `bg-white dark:bg-zinc-800 text-brand-600 dark:text-brand-400 border border-brand-500 dark:border-brand-400 hover:bg-brand-50 dark:hover:bg-zinc-700`,
	},
	form: {
		label: `block text-sm font-medium ${B} mb-1`,
		input: `w-full px-4 py-3 ${RD} border border-zinc-300 dark:border-zinc-700 bg-white dark:bg-zinc-950 text-zinc-900 dark:text-white focus:ring-2 focus:ring-brand-500 focus:border-brand-500 outline-none transition-all`,
		grid: "grid grid-cols-1 md:grid-cols-2 gap-6",
	},
	card: {
		base: "bg-white dark:bg-zinc-800 border border-zinc-100 dark:border-zinc-700 rounded-2xl shadow-sm transition-all duration-300 p-8",
		padded: "p-10",
		hover: "hover:shadow-xl hover:-translate-y-1 transition-all duration-300",
		highlight: "bg-brand-50 dark:bg-zinc-800 p-10 rounded-3xl transition-colors duration-300",
	},
	visual: {
		quote: "bg-brand-500 text-white p-6 rounded-xl italic shadow-lg dark:shadow-none",
		iconBox: `${RD} w-12 h-12 bg-brand-100 dark:bg-zinc-700 flex items-center justify-center transition-colors`,
		iconBoxRound: "w-12 h-12 bg-brand-100 dark:bg-zinc-800 rounded-full flex items-center justify-center flex-shrink-0 transition-colors duration-300",
		imagePlaceholder: "bg-zinc-100 dark:bg-zinc-700 rounded-3xl border-2 border-dashed border-zinc-300 dark:border-zinc-600 flex items-center justify-center",
		placeholderText: "text-zinc-600 dark:text-zinc-400 font-bold",
		avatarPlaceholder: "w-32 h-32 bg-zinc-100 dark:bg-zinc-700 rounded-full border-4 border-white dark:border-zinc-600 shadow-md flex-shrink-0 flex items-center justify-center",
		avatarAccent: "absolute -bottom-2 -right-2 bg-brand-500 w-8 h-8 rounded-full border-4 border-white dark:border-zinc-950",
		checkIcon: `h-5 w-5 ${ACTION} mt-0.5 flex-shrink-0`,
		checkIconWrapper: "mt-1 bg-brand-50 dark:bg-zinc-800 p-1 rounded-full",
		accentLine: "h-1 w-12 bg-brand-500 rounded-full",
		testimonialQuoteIcon: "absolute top-8 left-8 w-10 h-10 text-brand-100 dark:text-zinc-700 transform -translate-x-1/2 -translate-y-1/2",
		themeToggle: "text-zinc-500 hover:text-brand-600 focus:outline-none dark:text-zinc-400 dark:hover:text-brand-500 rounded-lg text-sm p-2.5 ml-4",
		svg4: "h-4 w-4",
		svg6: "h-6 w-6",
		m6: M6,
		m12: M12,
	},
	blog: {
		searchWrapper: "relative w-full md:w-64",
		searchIcon: "absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none",
		searchIconSvg: `w-4 h-4 text-zinc-500 dark:text-zinc-400`,
		postItem: "group post-item",
		postTitle: `${H} text-2xl font-bold group-hover:text-brand-600 dark:group-hover:text-brand-400 transition-colors mb-4`,
	},
};