name: Index

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  testing:
    uses: apollogeddon/forgejs/.github/workflows/testing.yml@main
    with:
      node_version: '22'
      working_directory: '.'
    permissions:
      contents: write
      pull-requests: write
      packages: read
    secrets: inherit

  release:
    needs: testing
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    uses: apollogeddon/forgejs/.github/workflows/version.yml@main
    permissions:
      contents: write
      pull-requests: write
      pages: write
      id-token: write
    secrets: inherit
